In [17]:
import numpy as np
import pandas as pd
fullData = pd.read_csv('data/churn_train.csv')
fullData.head()

,avg_dist,avg_rating_by_driver,avg_rating_of_driver,avg_surge,city,last_trip_date,phone,signup_date,surge_pct,trips_in_first_30_days,luxury_car_user,weekday_pct
0,6.94,5.0,5.0,1.00,Astapor,2014-05-03,Android,2014-01-12,0.0,0,False,100.0
1,8.06,5.0,5.0,1.00,Astapor,2014-01-26,Android,2014-01-25,0.0,2,True,0.0
2,21.50,4.0,NaN,1.00,Winterfell,2014-05-21,iPhone,2014-01-02,0.0,1,True,100.0
3,9.46,5.0,NaN,2.75,Winterfell,2014-01-10,Android,2014-01-09,100.0,1,False,100.0
4,13.77,5.0,NaN,1.00,Winterfell,2014-05-13,iPhone,2014-01-31,0.0,0,False,100.0

In [18]:
fullData['last_trip_date'] = pd.to_datetime(fullData['last_trip_date'])
fullData['signup_date'] = pd.to_datetime(fullData['signup_date'])
condition = fullData['last_trip_date'] < '2014-06-01'
fullData['churn'] = 1
fullData.ix[~condition, 'churn'] = 0
fullData.head(20)

,avg_dist,avg_rating_by_driver,avg_rating_of_driver,avg_surge,city,last_trip_date,phone,signup_date,surge_pct,trips_in_first_30_days,luxury_car_user,weekday_pct,churn
0,6.94,5.0,5.0,1.00,Astapor,2014-05-03,Android,2014-01-12,0.0,0,False,100.0,1
1,8.06,5.0,5.0,1.00,Astapor,2014-01-26,Android,2014-01-25,0.0,2,True,0.0,1
2,21.50,4.0,NaN,1.00,Winterfell,2014-05-21,iPhone,2014-01-02,0.0,1,True,100.0,1
3,9.46,5.0,NaN,2.75,Winterfell,2014-01-10,Android,2014-01-09,100.0,1,False,100.0,1
4,13.77,5.0,NaN,1.00,Winterfell,2014-05-13,iPhone,2014-01-31,0.0,0,False,100.0,1
5,14.51,5.0,NaN,1.00,Astapor,2014-04-22,iPhone,2014-01-29,0.0,0,True,100.0,1
6,4.87,4.7,4.0,1.00,Astapor,2014-04-21,Android,2014-01-18,0.0,0,False,66.7,1
7,1.78,4.0,5.0,1.00,Winterfell,2014-01-12,iPhone,2014-01-11,0.0,3,False,0.0,1
8,6.87,5.0,4.7,1.00,Astapor,2014-01-30,Android,2014-01-01,0.0,3,False,66.7,1
9,2.41,5.0,3.0,1.00,Winterfell,2014-01-29,iPhone,2014-01-28,0.0,1,False,100.0,1
10,3.96,5.0,NaN,2.00,Winterfell,2014-01-19,iPhone,2014-01-18,100.0,1,False,0.0,1
11,17.04,5.0,NaN,1.00,Winterfell,2014-05-12,Android,2014-01-26,0.0,0,True,100.0,1
12,5.42,4.7,5.0,1.00,Astapor,2014-06-28,iPhone,2014-01-05,0.0,2,True,33.3,0
13,5.02,5.0,5.0,1.00,Astapor,2014-01-19,Android,2014-01-19,0.0,1,False,0.0,1
14,4.28,5.0,4.0,1.15,Winterfell,2014-06-28,Android,2014-01-14,20.0,2,False,40.0,0
15,3.40,5.0,5.0,1.00,Astapor,2014-01-16,Android,2014-01-16,0.0,1,True,100.0,1
16,6.74,4.8,3.7,1.02,Winterfell,2014-05-30,iPhone,2014-01-25,9.1,2,False,54.5,1
17,7.27,4.8,4.0,1.00,Winterfell,2014-05-15,iPhone,2014-01-07,0.0,1,False,75.0,1
18,2.72,4.7,4.5,1.00,Astapor,2014-04-13,iPhone,2014-01-10,0.0,1,False,33.3,1
19,5.94,5.0,5.0,1.00,Astapor,2014-03-06,iPhone,2014-01-26,0.0,1,True,100.0,1

In [19]:
float(sum(fullData['churn']))/float(len(fullData))

0.6242

In [30]:
fullData['signup_date'].min()

Timestamp('2014-01-01 00:00:00')

In [21]:
fullData.describe()

,avg_dist,avg_rating_by_driver,avg_rating_of_driver,avg_surge,surge_pct,trips_in_first_30_days,weekday_pct,churn
count,40000.000000,39838.000000,33472.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000
mean,5.791302,4.777434,4.601697,1.074956,8.857342,2.280700,60.874382,0.624200
std,5.708056,0.448088,0.614810,0.222427,20.014008,3.811289,37.089619,0.484335
min,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,2.420000,4.700000,4.300000,1.000000,0.000000,0.000000,33.300000,0.000000
50%,3.880000,5.000000,4.900000,1.000000,0.000000,1.000000,66.700000,1.000000
75%,6.930000,5.000000,5.000000,1.050000,8.300000,3.000000,100.000000,1.000000
max,160.960000,5.000000,5.000000,8.000000,100.000000,125.000000,100.000000,1.000000

In [22]:
fullData.fillna(fullData.mean())

,avg_dist,avg_rating_by_driver,avg_rating_of_driver,avg_surge,city,last_trip_date,phone,signup_date,surge_pct,trips_in_first_30_days,luxury_car_user,weekday_pct,churn
0,6.94,5.0,5.000000,1.00,Astapor,2014-05-03,Android,2014-01-12,0.0,0,False,100.0,1
1,8.06,5.0,5.000000,1.00,Astapor,2014-01-26,Android,2014-01-25,0.0,2,True,0.0,1
2,21.50,4.0,4.601697,1.00,Winterfell,2014-05-21,iPhone,2014-01-02,0.0,1,True,100.0,1
3,9.46,5.0,4.601697,2.75,Winterfell,2014-01-10,Android,2014-01-09,100.0,1,False,100.0,1
4,13.77,5.0,4.601697,1.00,Winterfell,2014-05-13,iPhone,2014-01-31,0.0,0,False,100.0,1
5,14.51,5.0,4.601697,1.00,Astapor,2014-04-22,iPhone,2014-01-29,0.0,0,True,100.0,1
6,4.87,4.7,4.000000,1.00,Astapor,2014-04-21,Android,2014-01-18,0.0,0,False,66.7,1
7,1.78,4.0,5.000000,1.00,Winterfell,2014-01-12,iPhone,2014-01-11,0.0,3,False,0.0,1
8,6.87,5.0,4.700000,1.00,Astapor,2014-01-30,Android,2014-01-01,0.0,3,False,66.7,1
9,2.41,5.0,3.000000,1.00,Winterfell,2014-01-29,iPhone,2014-01-28,0.0,1,False,100.0,1
10,3.96,5.0,4.601697,2.00,Winterfell,2014-01-19,iPhone,2014-01-18,100.0,1,False,0.0,1
11,17.04,5.0,4.601697,1.00,Winterfell,2014-05-12,Android,2014-01-26,0.0,0,True,100.0,1
12,5.42,4.7,5.000000,1.00,Astapor,2014-06-28,iPhone,2014-01-05,0.0,2,True,33.3,0
13,5.02,5.0,5.000000,1.00,Astapor,2014-01-19,Android,2014-01-19,0.0,1,False,0.0,1
14,4.28,5.0,4.000000,1.15,Winterfell,2014-06-28,Android,2014-01-14,20.0,2,False,40.0,0
15,3.40,5.0,5.000000,1.00,Astapor,2014-01-16,Android,2014-01-16,0.0,1,True,100.0,1
16,6.74,4.8,3.700000,1.02,Winterfell,2014-05-30,iPhone,2014-01-25,9.1,2,False,54.5,1
17,7.27,4.8,4.000000,1.00,Winterfell,2014-05-15,iPhone,2014-01-07,0.0,1,False,75.0,1
18,2.72,4.7,4.500000,1.00,Astapor,2014-04-13,iPhone,2014-01-10,0.0,1,False,33.3,1
19,5.94,5.0,5.000000,1.00,Astapor,2014-03-06,iPhone,2014-01-26,0.0,1,True,100.0,1
20,17.34,5.0,5.000000,1.00,Winterfell,2014-01-15,Android,2014-01-14,0.0,1,True,100.0,1
21,3.31,4.8,3.700000,1.02,King's Landing,2014-05-30,iPhone,2014-01-28,2.6,9,False,47.4,1
22,2.69,4.3,5.000000,1.00,Winterfell,2014-04-21,iPhone,2014-01-15,0.0,0,False,0.0,1
23,6.00,5.0,4.601697,1.00,Winterfell,2014-01-10,iPhone,2014-01-07,0.0,1,False,100.0,1
24,4.96,5.0,5.000000,1.00,Winterfell,2014-02-17,iPhone,2014-01-26,0.0,1,False,100.0,1
25,11.44,4.6,4.700000,1.00,Astapor,2014-06-09,iPhone,2014-01-25,0.0,6,True,31.4,0
26,0.05,5.0,5.000000,1.00,Winterfell,2014-01-12,Android,2014-01-12,0.0,1,False,0.0,1
27,3.70,4.6,5.000000,1.00,Winterfell,2014-05-23,iPhone,2014-01-04,0.0,2,False,40.0,1
28,3.89,5.0,4.000000,1.00,Astapor,2014-04-13,iPhone,2014-01-03,0.0,0,False,0.0,1
29,4.70,4.8,3.300000,1.00,Astapor,2014-01-19,Android,2014-01-06,0.0,4,False,25.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
39970,6.65,5.0,4.000000,1.75,Winterfell,2014-06-29,iPhone,2014-01-23,66.7,2,False,33.3,0
39971,13.45,5.0,4.601697,1.00,King's Landing,2014-02-26,Android,2014-01-08,0.0,0,True,100.0,1
39972,1.95,3.5,5.000000,1.50,Astapor,2014-02-14,iPhone,2014-01-25,100.0,2,False,100.0,1
39973,4.67,5.0,5.000000,1.00,Astapor,2014-06-26,iPhone,2014-01-06,0.0,0,True,62.5,0
39974,1.74,4.3,4.900000,1.01,Astapor,2014-06-11,iPhone,2014-01-17,4.5,9,True,95.5,0
39975,1.16,5.0,4.601697,1.00,Astapor,2014-01-18,iPhone,2014-01-18,0.0,1,True,0.0,1
39976,3.21,4.7,4.800000,1.01,Winterfell,2014-06-29,iPhone,2014-01-07,2.8,9,False,55.6,0
39977,2.05,4.0,5.000000,1.00,Astapor,2014-06-29,iPhone,2014-01-18,0.0,0,False,0.0,0
39978,5.59,5.0,5.000000,1.25,Astapor,2014-04-12,Android,2014-01-27,50.0,1,False,50.0,1
39979,10.50,5.0,3.500000,1.00,Winterfell,2014-01-25,iPhone,2014-01-20,0.0,3,True,66.7,1
39980,4.48,4.0,4.601697,1.00,Astapor,2014-05-11,iPhone,2014-01-21,0.0,1,True,50.0,1
39981,1.13,5.0,5.000000,1.75,King's Landing,2014-01-11,Android,2014-01-11,100.0,1,False,0.0,1
39982,1.99,4.8,4.800000,1.15,Winterfell,2014-04-25,iPhone,2014-01-06,20.0,3,False,50.0,1
39983,9.14,4.0,4.601697,1.00,Astapor,2014-01-31,iPhone,2014-01-30,0.0,1,True,100.0,1
39984,2.07,4.5,5.000000,1.00,Winterfell,2014-04-11,iPhone,2014-01-18,0.0,2,False,87.5,1
39985,15.95,5.0,4.000000,1.00,Winterfell,2014-01-15,iPhone,2014-01-15,0.0,1,True,100.0,1
39986,12.10,5.0,4.000000,1.00,Astapor,2014-06-28,iPhone,2014-01-22,0.0,2,False,75.0,0
39987,3.29,5.0,4.500000,1.50,Winterfell,2014-02-01,iPhone,2014-01-05,50.0,2,False,100.0,1
39988,4.53,4.6,4.700000,1.41,Winterfell,2014-05-30,iPhone,2014-01-06,18.8,7,False,75.0,1
39989,2.67,4.9,4.300000,1.06,Astapor,2014-05-23,Android,2014-01-15,11.1,3,True,88.9,1
39990,9.45,4.8,5.000000,1.00,Winterfell,2014-01-25,iPhone,2014-01-23,0.0,4,True,75.0,1
39991,3.01,5.0,5.000000,1.00,Astapor,2014-06-21,iPhone,2014-01-01,0.0,0,False,0.0,0
39992,2.71,3.0,3.000000,1.25,King's Landing,2014-02-15,Android,2014-01-26,100.0,1,True,0.0,1
39993,6.89,5.0,5.000000,1.00,Winterfell,2014-01-04,Android,2014-01-03,0.0,1,False,100.0,1
39994,3.88,4.8,5.000000,1.00,Astapor,2014-06-27,Android,2014-01-16,0.0,2,False,100.0,0
39995,2.06,4.8,4.300000,1.08,Winterfell,2014-04-02,Android,2014-01-26,9.5,8,False,90.5,1
39996,2.05,5.0,5.000000,1.00,King's Landing,2014-05-09,iPhone,2014-01-08,0.0,2,False,85.7,1
39997,3.04,5.0,5.000000,1.00,Winterfell,2014-06-24,Android,2014-01-04,0.0,3,True,33.3,0
39998,3.49,4.3,3.300000,1.50,Astapor,2014-02-09,iPhone,2014-01-08,40.0,5,False,60.0,1
39999,4.25,4.7,5.000000,1.00,Astapor,2014-06-27,iPhone,2014-01-18,0.0,2,True,42.9,0

In [29]:
print (fullData['last_trip_date'][3] - fullData['signup_date'][3]).days == 1

True

In [31]:
fullData.head()

,avg_dist,avg_rating_by_driver,avg_rating_of_driver,avg_surge,city,last_trip_date,phone,signup_date,surge_pct,trips_in_first_30_days,luxury_car_user,weekday_pct,churn
0,6.94,5.0,5.0,1.00,Astapor,2014-05-03,Android,2014-01-12,0.0,0,False,100.0,1
1,8.06,5.0,5.0,1.00,Astapor,2014-01-26,Android,2014-01-25,0.0,2,True,0.0,1
2,21.50,4.0,NaN,1.00,Winterfell,2014-05-21,iPhone,2014-01-02,0.0,1,True,100.0,1
3,9.46,5.0,NaN,2.75,Winterfell,2014-01-10,Android,2014-01-09,100.0,1,False,100.0,1
4,13.77,5.0,NaN,1.00,Winterfell,2014-05-13,iPhone,2014-01-31,0.0,0,False,100.0,1

Timestamp('2014-07-01 00:00:00')